### ISSUE TITLE
Error installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by fidget324** [esteve/ros2_java#44]
I'm trying to build using
```
$ ament build --symlink-install --isolated
```
It builds several repos without any issues, but then fails when it gets to the `test_msgs` installation. I get the error:
```
cannot create directory '//test_msgs'
```
I dug into the CMake a little bit, and it seems that somewhere the path is not "isolated" and becomes the root of the filesystem: "/". I'm not sure if this is an issue with this repo, or one of the subrepos...

UPDATE: I dug into your most recent travis-ci build for xenial, and found the same lines that were giving me problems (the lines with the *.py scripts):
```
-- Symlinking: /home/travis/build/output/install_isolated_java/test_msgs/share/test_msgs/srv/Empty_Request.msg
-- Symlinking: /home/travis/build/output/install_isolated_java/test_msgs/share/test_msgs/srv/Empty_Response.msg
-- Symlinking: /home/travis/build/output/install_isolated_java/test_msgs/share/test_msgs/srv/Primitives_Request.msg
-- Symlinking: /home/travis/build/output/install_isolated_java/test_msgs/share/test_msgs/srv/Primitives_Response.msg
-- Symlinking: //test_msgs/__init__.py
-- Symlinking: //test_msgs/message_fixtures.py
-- Symlinking: //test_msgs/service_fixtures.py
-- Symlinking: /home/travis/build/output/install_isolated_java/test_msgs/include/test_msgs/message_fixtures.hpp
-- Symlinking: /home/travis/build/output/install_isolated_java/test_msgs/include/test_msgs/service_fixtures.hpp
```
This doesn't look right to me.

**Comment by esteve** [comment]
Sorry for the really slow response. I've submitted https://github.com/ros2/rcl_interfaces/pull/37 which should fix this.

**Comment by esteve** [comment]
Now that ros2/rcl_interfaces#37 has been merged, I'll close this ticket. Please reopen it if you still see this error. Thanks.

**Comment by fidget324** [comment]
I'm still getting the error. I also see the same issue in your latest Travis build for xenial. Please reopen.

**Comment by fsal33m** [comment]
@esteve I'm seeing the same issue.

**Comment by esteve** [comment]
Given the bug is in `rcl_interfaces` and not in `ros2-java`, there's not much that can be done except switching to the master branch in `rcl_interfaces` to pick up the change. I've changed the repos files to use the `master` branch of `rcl_interfaces`. Please let me know if it works for you.
